### PR TITLE
adding in missing olmconfig file

### PR DESCRIPTION
**Pull request by acornett21**
Signed-off-by: Adam D. Cornett <adc@redhat.com>

Issue #, if available:
- Fixes: aws-controllers-k8s/community#1081
Description of changes:
Adding in the prestaged olm file so that bundle generation occurs properly.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by acornett21** [comment]
@vijtrip2 @RedbackThomson Can one of you see why the tests are failing? This change shouldn't affect the runtime at all. Based on the logs it looks like the controller can't find the ecr instance created, then it finds it but it appears to be associated to another IAM. Maybe previous tests did not clear up things in AWS? Just some thoughts.

**Comment by jaypipes** [comment]
actually, I think it's @A-Hilaly that needs to look into these failing tests. I suspect it's something to do with leftover ECR repositories not being cleaned up from a test run somewhere.

**Pull request merged**
