### PR TITLE
Regenerates the ECR controller with `ack-generate` v0.3.1

### PR DESCRIPTION
**Pull request by A-Hilaly**
Regenerates the ECR controller with `ack-generate` v0.3.1` to get to ACK runtime v0.3.0

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by A-Hilaly** [comment]
@aws-controllers-k8s/runtime-maintainer looks like runtime `v0.2.3` broke ecr-controller e2e tests - currently investigating it the root cause..

**Comment by surajkota** [comment]
https://github.com/aws-controllers-k8s/community/issues/825

**Comment by A-Hilaly** [comment]
Ok fixed, the controller had out dated custom update function.

**Review by jaypipes — APPROVED** [review]
:+1:

**Pull request merged**
